# Generated by Django 4.1.3 on 2022-12-23 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("NewsTitle", models.CharField(max_length=100)),
                ("Count", models.IntegerField()),
                (
                    "NewsClass",
                    models.CharField(
                        choices=[
                            ("S", "Sport"),
                            ("H", "Health"),
                            ("P", "Politics"),
                            ("E", "Economics"),
                            ("T", "Technology"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
        ),
    ]
