# Generated by Django 4.1.3 on 2022-12-25 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_news_newsbody_alter_news_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="slug",
            field=models.SlugField(max_length=200, null=True),
        ),
    ]
