# Generated by Django 4.1.3 on 2022-12-26 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_news_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="news",
            old_name="Count",
            new_name="ViewCounter",
        ),
    ]
